### ISSUE TITLE
Github handler

### ISSUE THREAD

**Issue by ad12** [ad12/meddlr#9]
Add a handler to download, cache, and map github files to path on the local machine. This is useful for annotation files, config files, etc.

### TODOs
- [x] Change annotation file caching to follow this api
- [x] Add support for config files
- [x] verify this works with the command line process of handling configuration files
